### ISSUE TITLE
Doesn't work on FireFox?

### ISSUE THREAD

**Issue by Jakobud** [frexy/svg-sprite-polyfill#4]
Why doesn't this work on Firefox? I'm on FireFox 39. `active` returns false since it doesn't match any of the UserAgents.

Now, the sprites work fine using FireFox, meaning that they show up okay. But you cannot alter them using CSS since they are referencing an external file. This is normal for SVGs. You cannot use CSS to alter the colors of an externally referenced SVG.

The great thing about this Polyfill in Chrome is that it does its thing and you are able to apply css to any of the svgs because they are all now inline. 

Is there any way to force the polyfill to run no matter what browser you are in?

**Comment by chutichhuy** [comment]
Yes, this is a longgg story... This "polyfill" exists because in the begining, we thought that it's a Chrome's bug for not allowing CSS on the svg. But it's actually a Firefox's bug to allow CSS. Because we want the ability to use CSS, we have moved on with another solution, which is less a mistake, which is the component repo. I guess the newer version of Firefox has fixed that bug, so you're unable to style. 
One solution is to se the 'active' mark to true.

**Comment by Jakobud** [comment]
Yeah I totally understand that now. Thanks
